default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: ./.hooks/golangci-lint.sh
        language: script
        files: '\.go$'
        pass_filenames: false
      - id: courtney
        name: courtney
        entry: ./.hooks/courtney.sh
        language: script
        files: '\.go$'
        pass_filenames: false
