CREATE TABLE IF NOT EXISTS Users (
    Name TEXT PRIMARY KEY NOT NULL,
    PassHash BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS Intervals (
    Id SERIAL PRIMARY KEY,
    IntrStart TIMESTAMP WITH TIME ZONE NOT NULL,
    IntrEnd TIMESTAMP WITH TIME ZONE NOT NULL,
    Quality INTEGER NOT NULL,
    Username TEXT NOT NULL,
    FOREIGN KEY (Username) REFERENCES Users(Name)
);
