CREATE TABLE IF NOT EXISTS Users (
    Name TEXT PRIMARY KEY NOT NULL,
    PassHash BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS Intervals (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    IntrStart TEXT NOT NULL,
    IntrEnd TEXT NOT NULL,
    Quality INTEGER NOT NULL,
    Username TEXT NOT NULL,
    FOREIGN KEY (Username) REFERENCES Users(Name)
);

